services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    expose:
      - "3002"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
